# Generated by Django 5.0 on 2024-01-04 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userbase_company_customer_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='birth_date',
        ),
    ]
