# Generated by Django 5.0 on 2024-01-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='logo',
            field=models.ImageField(default='  ', upload_to='company_logos/'),
        ),
    ]
