# Generated by Django 5.0 on 2024-01-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customer_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='logo',
            field=models.ImageField(default='Customer_profile.webp', upload_to='customer_pictures/'),
        ),
    ]
