# Generated by Django 5.0 on 2024-01-04 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userbase_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='birth_date',
            new_name='date_of_birth',
        ),
    ]
