# Generated by Django 5.0 on 2024-01-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
