# Generated by Django 5.0 on 2024-01-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='requests_count',
            field=models.IntegerField(default=0),
        ),
    ]
