# Generated by Django 5.0 on 2024-01-12 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='complete',
            new_name='completed',
        ),
    ]
