# Generated by Django 5.0 on 2024-01-13 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_rename_complete_service_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='service',
            name='customers',
        ),
        migrations.RemoveField(
            model_name='service',
            name='date',
        ),
        migrations.AlterField(
            model_name='service',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
