# Generated by Django 5.0 on 2024-01-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_request_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='duration',
            field=models.IntegerField(default=1),
        ),
    ]
