# Generated by Django 5.0 on 2024-01-26 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_request_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
